site_name: UI5 Test Runner
site_url: "https://ArnaudBuchholz.github.io/ui5-test-runner/" # required for working 404 page
repo_name: "ArnaudBuchholz/ui5-test-runner"
repo_url: "https://github.com/ArnaudBuchholz/ui5-test-runner"
edit_uri: tree/main/docs/
docs_dir: "docs" # default
site_dir: "site" # default
nav:
  - Home: README.md
  - How to demo: demo.md
  - Command line usage: usage.md
  - Mapping v1 settings to v2: mapping_v1_v2.md
  - Serving and testing the application (a.k.a. legacy mode): legacy.md
  - Testing a "remote" application: testing.md
  - Coverage extraction: coverage.md
  - Configuration file: configuration.md
  - Tips & tricks: tipsNtricks.md
  - Browser instantiation command: browser.md
  - Automation Libraries:
    - puppeteer: puppeteer.md
    - jsdom: jsdom.md
    - playwright: playwright.md
    - selenium-webdriver: selenium-webdriver.md

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "blue"
  # logo: "images/logo.svg"
  # favicon: "images/favicon.png"
  font: false
  features:
    - navigation.expand
    - content.code.copy

# extra_css:
#   - 'stylesheets/extra.css'

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # PyMdown Extensions Documentation: https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

dev_addr: "localhost:8000"
