name: NPM Publish

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v7
      with:
        name: dist
        path: ./dist
        retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: 'npm'
    - run: |
          SEM_REL_VERSION=$(node -e "process.stdout.write(require('./package.json').devDependencies['semantic-release'])")
          npm install --prefix ./sr semantic-release@$SEM_REL_VERSION --no-save
    - uses: actions/download-artifact@v7
      with:
        name: dist
        path: ./dist
    - run: npx --prefix ./sr --no semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        npm_config_package_lock: false
        npm_config_ignore_scripts: true
        npm_config_workspaces_update: false
