name: NPM Publish

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v7
      with:
        name: dist
        path: ./dist
        retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: 'npm'
    - run: npm install --prefix ./sr semantic-release@25 @semantic-release/changelog@6 @semantic-release/git@10 --no-save
    - uses: actions/download-artifact@v7
      with:
        name: dist
        path: ./dist
    - run: |
          mv package.json package0.json
          jq 'del(.scripts,.devDependencies)' package0.json > package.json
          rm package0.json
          npx --prefix ./sr --no semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        npm_config_package_lock: false
        npm_config_ignore_scripts: true
        npm_config_workspaces_update: false
